# Generated by Django 3.0.8 on 2020-07-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intType', models.IntegerField()),
                ('stringType', models.CharField(max_length=32)),
                ('boolType', models.BooleanField()),
            ],
            options={
                'order_with_respect_to': 'intType',
            },
        ),
    ]
